export const ROLES = {
  ADMIN: 'ADMIN',
  TEAM: 'TEAM',
  ARTIST: 'ARTIST',
  CUSTOMER: 'CUSTOMER',
};

export const AUTO_PROFILE_ROLES = [
  ROLES.ADMIN,
  ROLES.TEAM,
  ROLES.ARTIST,
];

export const PROFILE_TYPE_BY_ROLE = {
  ADMIN: 'TEAM',
  TEAM: 'TEAM',
  ARTIST: 'ARTIST',
};
